// =============================================================================
// Vendor the web fonts.
//
// The game shipped with three <link> tags pointing at Google Fonts. In a
// packaged app that is a network request on first launch with no fallback if it
// fails, and on the web it is a third-party connection before the first frame.
// This pulls the woff2 files into public/fonts/ and writes the @font-face rules
// that point at them.
//
//   npm run fonts
//
// Re-run it only when the font list changes — the output is committed.
// =============================================================================
import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'public', 'fonts');
const CSS_OUT = join(ROOT, 'src', 'styles', 'fonts.css');

// A Chrome UA is what makes the API answer with woff2 rather than ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const SRC =
  'https://fonts.googleapis.com/css2' +
  '?family=Cinzel:wght@500;700' +
  '&family=Barlow+Condensed:wght@400;500;600' +
  '&display=swap';

// The HUD is English, but a player types their own commander name, so keep the
// accented Latin ranges. Everything else the API offers is dead weight here.
const SUBSETS = new Set(['latin', 'latin-ext']);

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

async function main() {
  const res = await fetch(SRC, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`font CSS: ${res.status} ${res.statusText}`);
  const css = await res.text();

  // The API emits one `/* subset */` comment before each @font-face block.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (!blocks.length) throw new Error('could not parse the font CSS');

  await mkdir(OUT_DIR, { recursive: true });

  const rules = [];
  let bytes = 0;

  for (const [, subset, block] of blocks) {
    if (!SUBSETS.has(subset)) continue;

    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!family || !weight || !url) throw new Error(`incomplete @font-face:\n${block}`);

    const name = `${slug(family)}-${weight}-${subset}.woff2`;
    const file = await fetch(url).then((r) => {
      if (!r.ok) throw new Error(`${name}: ${r.status}`);
      return r.arrayBuffer();
    });
    await writeFile(join(OUT_DIR, name), Buffer.from(file));
    bytes += file.byteLength;
    console.log(`  ${name}  ${(file.byteLength / 1024).toFixed(1)} kB`);

    rules.push(
      block
        .replace(/url\(https:[^)]+\.woff2\)/, `url('/fonts/${name}')`)
        .replace(/font-display:\s*swap;/, 'font-display: swap;')
        .replace(/\s*\n\s*/g, '\n  ')
        .replace(/\{\s*/, '{\n  ')
        .replace(/\s*\}$/, '\n}'),
    );
  }

  const header = [
    '/* Iron Front — self-hosted web fonts.',
    ' *',
    ' * Generated by scripts/vendor-fonts.mjs (npm run fonts). Do not edit by',
    ' * hand: change the family list in that script and re-run it. The files',
    ' * live in public/fonts/ and are served from the app origin, so a packaged',
    ' * app never reaches the network for text. */',
    '',
  ].join('\n');

  await writeFile(CSS_OUT, `${header}${rules.join('\n\n')}\n`);
  console.log(`\n${rules.length} faces, ${(bytes / 1024).toFixed(0)} kB total`);
  console.log(`wrote ${relative(ROOT, CSS_OUT)}`);
}

main().catch((err) => {
  console.error('vendor-fonts failed:', err.message);
  process.exit(1);
});
